### PR TITLE
Adding inboxBackgroundColor

### PR DESCRIPTION
**Pull request by RowenaRavenclawWithExtraClaws**
Adding inboxBackgroundColor prop for the input box component to support different color themes

### CODE REVIEW

**Review by ghoshnirmalya — APPROVED** [review]

**Comment by ghoshnirmalya** [comment]
@RowenaRavenclawWithExtraClaws Thank you.

**Comment by RowenaRavenclawWithExtraClaws** [comment]
> @RowenaRavenclawWithExtraClaws Thank you.

Thanks for approving my changes, I will add a similar prop to the dropdown component tomorrow. I should've added it with the recent changes but I thought it is better to add theme one by one.

I have a question, did the npm package get updated with these changes ?

**Comment by ghoshnirmalya** [comment]
> I have a question, did the npm package get updated with these changes ?

No. I'll do a manual release on npm soon. Would wait for your other PR before I do the release. Can you please add these props in the [readme file](https://github.com/ghoshnirmalya/react-search-box/blob/master/README.md) as well?

**Comment by RowenaRavenclawWithExtraClaws** [comment]
> > I have a question, did the npm package get updated with these changes ?
> 
> No. I'll do a manual release on npm soon. Would wait for your other PR before I do the release. Can you please add these props in the [readme file](https://github.com/ghoshnirmalya/react-search-box/blob/master/README.md) as well?

Yeah, of course

**Pull request merged**
